### PR TITLE
GNU/Hurd: use mach debug API to convert virtual addresses to physical

### PR DESCRIPTION
**Pull request by luckyluke**
This is needed for some drivers e.g. virtio.

### CODE REVIEW

**Comment by anttikantee** [comment]
I think @robertmillan should review & merge this.  However, a few comments:
1) it would be nice to use the same indentation style
2) what is the significance of the 256 hardcoded limit?

**Comment by luckyluke** [comment]
1) you're right, i forced an update of the branch, it should be better now
2) It's an upper bound of what was needed on my tests (with virtio ld driver, reading and writing 512 bytes at a time).

**Comment by anttikantee** [comment]
Is there no `mach_vm` call which would actually honor vaddr, or a possibility to loop? (nb. don't take this interrogation as a sign that the patch may be rejected, I just want the patch to be the best it can be with reasonable effort)

**Comment by luckyluke** [comment]
I think no, at least I couldn't find a better mach_vm call; the only way to get the physical address is using the debug API, which seems to be enabled by default (e.g. on Debian).
Do you mean to loop over chunks of 256 page info at a time, just in case there are more than 256 pages?

**Comment by anttikantee** [comment]
@robertmillan said in email that he's busy, so I'm merging this now.

@luckyluke are you somehow affiliated with HURD and can push the improvement upstream?

**Comment by luckyluke** [comment]
@anttikantee  I'm not an official developer, however I can ask for comments on HURD channels

**Comment by anttikantee** [comment]
Thanks!

**Pull request merged**
